import { StyleSheet } from 'react-native';
import { Colors, FontWeights, TextSizes } from 'src/styles';

export const styles = StyleSheet.create({
  modalContentWrap: {
  },
  generatedContainer: {
    // maxHeight: '100%',
    display: 'flex',
    flexDirection: 'column',
    padding: 16,
    gap: 12,
  },
  generatedHeaderRow: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 4,
  },
  generatedReadyText: {
    ...TextSizes.medium,
    fontWeight: FontWeights.semibold,
    color: Colors.backgroundAccent,
  },
  retryText: {
    ...TextSizes.medium,
    fontWeight: FontWeights.medium,
    color: Colors.backgroundAccent3,
  },
  headerActions: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 16,
  },
  selectAllText: {
    ...TextSizes.medium,
    fontWeight: FontWeights.medium,
    color: Colors.backgroundAccent,
  },
  generatedListWrap: {
    maxHeight: 350,
  },
  generatedListContent: {
    display: 'flex',
    flexDirection: 'column',
    gap: 10,
    paddingBottom: 4,
  },
  generatedCard: {
    backgroundColor: Colors.backgroundLight4,
    borderRadius: 12,
    paddingVertical: 10,
    paddingHorizontal: 12,
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 10,
  },
  generatedCardUnchecked: {
    opacity: 0.5,
  },
  checkbox: {
    width: 22,
    height: 22,
    borderRadius: 6,
    borderWidth: 2,
    borderColor: Colors.textForeground,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 2,
  },
  checkboxChecked: {
    backgroundColor: Colors.backgroundAccent3,
    borderColor: Colors.backgroundAccent3,
  },
  checkmark: {
    fontSize: 12,
    fontWeight: FontWeights.bold,
    color: Colors.textSecondary,
    lineHeight: 14,
  },
  checkboxColumn: {
    paddingTop: 2,
  },
  editInput: {
    ...TextSizes.medium,
    fontWeight: FontWeights.bold,
    color: Colors.textPrimary,
    backgroundColor: Colors.backgroundSecondary,
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 6,
    minHeight: 36,
  },
  editInputAnswer: {
    fontWeight: FontWeights.regular,
    ...TextSizes.small,
    color: Colors.textForeground,
  },
  editDoneText: {
    ...TextSizes.small,
    fontWeight: FontWeights.semibold,
    color: Colors.backgroundAccent3,
    alignSelf: 'flex-end',
    marginTop: 2,
  },
  generatedBadge: {
    width: 24,
    height: 24,
    borderRadius: 8,
    backgroundColor: Colors.backgroundAccent3,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 2,
  },
  generatedBadgeText: {
    ...TextSizes.small,
    fontWeight: FontWeights.bold,
    color: Colors.textSecondary,
  },
  generatedTextWrap: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    gap: 2,
  },
  generatedQuestion: {
    ...TextSizes.medium,
    fontWeight: FontWeights.bold,
    color: Colors.textPrimary,
  },
  generatedAnswer: {
    ...TextSizes.small,
    fontWeight: FontWeights.regular,
    color: Colors.textForeground,
  },
  generatedButtonsRow: {
    display: 'flex',
    flexDirection: 'row',
    gap: 12,
    marginTop: 4,
  },
  backButton: {
    flex: 1,
    minHeight: 52,
    borderRadius: 12,
    backgroundColor: Colors.backgroundSecondary,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  backButtonText: {
    ...TextSizes.medium,
    fontWeight: FontWeights.semibold,
    color: Colors.textPrimary,
  },
  addAllButton: {
    flex: 1,
    minHeight: 52,
    borderRadius: 12,
    backgroundColor: Colors.backgroundAccent,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  addAllButtonText: {
    ...TextSizes.medium,
    fontWeight: FontWeights.semibold,
    color: Colors.textSecondary,
  },
  loadingContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 8,
    gap: 12,
    paddingTop: 40,
    paddingBottom: 24,
  },
  loadingIconWrap: {
    width: 112,
    height: 112,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 8,
  },
  loadingPulse: {
    position: 'absolute',
    width: 112,
    height: 112,
   
    borderRadius: 999,
    backgroundColor: Colors.backgroundAccent3,
  },
  loadingIconCircle: {
    width: 96,
    height: 96,
    borderRadius: 999,
    backgroundColor: Colors.backgroundAccent3,
    alignItems: 'center',
    justifyContent: 'center',
  },
  loadingTitle: {
    ...TextSizes.xxlarge,
    fontWeight: FontWeights.bold,
    color: Colors.textPrimary,
    textAlign: 'center',
  },
  loadingSubtitle: {
    ...TextSizes.medium,
    fontWeight: FontWeights.regular,
    color: Colors.textForeground,
    textAlign: 'center',
  },
  loadingProgressTrack: {
    width: '100%',
    height: 8,
    borderRadius: 999,
    overflow: 'hidden',
    backgroundColor: Colors.backgroundSecondary,
    marginTop: 8,
  },
  loadingProgressFill: {
    width: '22%',
    height: '100%',
    borderRadius: 999,
    backgroundColor: Colors.backgroundAccent3,
  },
  loadingStepText: {
    ...TextSizes.large,
    fontWeight: FontWeights.regular,
    color: Colors.textForeground,
    textAlign: 'center',
  },
  container: {
    display: 'flex',
    flexDirection: 'column',
    gap: 16,
    paddingHorizontal: 16,
    paddingTop: 4,
    paddingBottom: 16,
  },
  headerRow: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  iconBox: {
    width: 40,
    height: 40,
    borderRadius: 12,
    backgroundColor: Colors.backgroundAccent3,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerTextWrap: {
    display: 'flex',
    flexDirection: 'column',
    gap: 2,
    flexShrink: 1,
  },
  title: {
    ...TextSizes.large,
    fontWeight: FontWeights.bold,
    color: Colors.textPrimary,
  },
  subtitle: {
    ...TextSizes.xsmall,
    fontWeight: FontWeights.regular,
    color: Colors.textForeground,
  },
  fieldWrap: {
    display: 'flex',
    flexDirection: 'column',
  },
  input: {
    minHeight: 132,
    maxHeight: 200,
    borderRadius: 12,
    backgroundColor: Colors.backgroundSecondary,
    borderWidth: 1,
    borderColor: 'transparent',
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 12,
    color: Colors.textPrimary,
    ...TextSizes.small,
    fontWeight: FontWeights.regular,
  },
  inputFocused: {
    borderColor: Colors.backgroundAccent3,
  },
  counter: {
    marginTop: 6,
    textAlign: 'right',
    ...TextSizes.xsmall,
    fontWeight: FontWeights.regular,
    color: Colors.textForeground,
  },
  generateButton: {
    backgroundColor: Colors.backgroundAccent3,
    borderRadius: 12,
    minHeight: 52,
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    marginTop: 8,
  },
  generateButtonText: {
    ...TextSizes.medium,
    fontWeight: FontWeights.semibold,
    color: Colors.textSecondary,
  },
});
